# Rubocop config.
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - '**/Gemfile'
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.4
  # TargetRailsVersion: 5.1

# Use %r in regular expression
Style/RegexpLiteral:
  Enabled: false

# Use %w or %W for arrays of words.
Style/WordArray:
  Enabled: false

# Do not use symbol array
Style/SymbolArray:
  Enabled: false

# Document classes and non-namespace modules
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# don't really care how we define exponents if we ever do
Style/ExponentialNotation:
  Enabled: false

# use each_key and each value over keys.each and values.each
Style/HashEachMethods:
  Enabled: true

# ruby 2.5 required
Style/HashTransformKeys:
  Enabled: false

# ruby 2.4 required
Style/HashTransformValues:
  Enabled: false

# ruby 2.6 required
Style/SlicingWithRange:
  Enabled: false

Layout/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
  # Change the default 80 chars limit value
  Max: 120
  # If you want the rule only apply to a specific folder/file
  Include:
    - 'app/**/*'
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'db/schema.rb'

# Empty lines around attr_accessor, attr_reader, attr_writer, etc
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# No spaces after the dot when calling a method, IE no "test. this"
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# Don't mind us using the general Exception class
Lint/RaiseException:
  Enabled: false

# This cop checks unexpected overrides
Lint/StructNewOverride:
  Enabled: true
